#!/bin/bash
# dac-setup.sh — detect USB DACs, give them stable ALSA names, enable native DSD where the kernel
# allows it, and record their capabilities for gen-mpd-conf.sh.
#
#   sudo ./dac-setup.sh                 detect, write /etc/hifi/dacs.conf and the udev rule
#   sudo ./dac-setup.sh --try-native-dsd  also reload snd-usb-audio with the DSD_RAW quirk when a DAC
#                                       advertises a raw-DSD alt-setting the kernel did not enable
#   sudo ./dac-setup.sh --name 2fc6:f802=ES9039   force an ALSA id for a VID:PID (repeatable)
#   sudo ./dac-setup.sh --show          print detected DACs and exit
#
# Works with any USB Audio Class device. Tested: Comtrue-bridge ES9039 dongle (2fc6:f802) on
# Orange Pi Zero 3 / Debian 12 (kernel 6.1): native DSD needs quirk_flags=0x8000.

DIR=$(cd "$(dirname "$0")" && pwd); . "$DIR/lib.sh"
need_root

TRY_DSD=0; SHOW=0; declare -A FORCE_NAME
while [ $# -gt 0 ]; do
  case "$1" in
    --try-native-dsd) TRY_DSD=1;;
    --show) SHOW=1;;
    --name) FORCE_NAME[${2%%=*}]=${2##*=}; shift;;
    *) die "unknown option $1";;
  esac; shift
done

command -v amixer >/dev/null || die "alsa-utils is not installed"
mapfile -t CARDS < <(usb_audio_cards)
[ ${#CARDS[@]} -gt 0 ] || die "no USB audio device found (lsusb / dmesg | grep snd-usb-audio)"

# ---- optional: enable native DSD via the snd-usb-audio quirk ------------------------------
if [ $TRY_DSD -eq 1 ]; then
  need_quirk=0; already_native_via_quirk=0
  for line in "${CARDS[@]}"; do IFS='|' read -r idx id vid pid name <<<"$line"
    st=$(card_dsd_state "$idx")
    [ "$st" = raw ] && need_quirk=1
    [ "$st" = native ] && quirk_currently_set && already_native_via_quirk=1
  done
  write_quirk_conf() {
    if [ "$(kernel_ver)" -ge 618 ]; then
      opts=""; for line in "${CARDS[@]}"; do IFS='|' read -r idx id vid pid name <<<"$line"
        [ "$(card_dsd_state "$idx")" != none ] && opts="${opts:+$opts;}$vid:$pid:dsd_raw"; done
      echo "options snd-usb-audio quirk_flags=$opts" > /etc/modprobe.d/hifi-dsd.conf
    else
      # legacy form (kernels < 6.18): one 0x8000 per probe slot. Only alt-settings that advertise
      # raw DSD are affected, so applying it to every slot is safe for DACs without DSD.
      echo "options snd-usb-audio quirk_flags=0x8000,0x8000,0x8000,0x8000" > /etc/modprobe.d/hifi-dsd.conf
    fi
  }
  if [ $already_native_via_quirk -eq 1 ] && [ ! -f /etc/modprobe.d/hifi-dsd.conf ]; then
    write_quirk_conf; log "native DSD is active through a manually set quirk; persisted it in /etc/modprobe.d/hifi-dsd.conf"
  fi
  if [ $need_quirk -eq 1 ]; then
    write_quirk_conf
    log "wrote /etc/modprobe.d/hifi-dsd.conf; reloading snd-usb-audio (playback must be stopped)"
    if systemctl is-active --quiet mpd; then systemctl stop mpd; RESTART_MPD=1; fi
    if rmmod snd_usb_audio 2>/dev/null; then
      modprobe snd_usb_audio && sleep 3
    else
      warn "snd_usb_audio is busy; the quirk will apply after a reboot"
    fi
    [ "${RESTART_MPD:-0}" = 1 ] && systemctl start mpd
    mapfile -t CARDS < <(usb_audio_cards)
  else
    log "every USB DAC either already offers native DSD or has no raw-DSD alt-setting; no quirk needed"
  fi
fi

# ---- record capabilities + write the udev rule ---------------------------------------------
mkdir -p "$HIFI_ETC"
RULE=/etc/udev/rules.d/90-hifi-dac.rules
{ echo "# generated by dac-setup.sh on $(date -Is); stable ALSA ids for USB DACs"
  echo '# hot-plug hook: any USB sound card add/remove -> hifid rescan (harmless if hifid is absent)'
  echo 'SUBSYSTEM=="sound", KERNEL=="card*", SUBSYSTEMS=="usb", ACTION=="add|remove", TAG+="systemd", RUN+="/bin/systemctl --no-block start hifid-dac-hotplug@%k.service"'
} > "$RULE.tmp"
: > "$HIFI_DACS_CONF.tmp"

n=0
for line in "${CARDS[@]}"; do
  IFS='|' read -r idx id vid pid name <<<"$line"
  n=$((n+1))
  alsa=${FORCE_NAME[$vid:$pid]:-}
  [ -z "$alsa" ] && alsa=$(alsa_id_from "$name")
  [ -z "$alsa" ] && alsa="usb${vid}${pid}"
  rates=$(card_rates "$idx"); bits=$(card_max_bits "$idx"); dsd=$(card_dsd_state "$idx"); mixer=$(card_mixer_control "$idx")
  maxrate=$(echo "$rates" | tr ' ' '\n' | sort -n | tail -1)
  printf 'SUBSYSTEM=="sound", KERNEL=="card*", ACTION=="add", ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s", ATTR{id}="%s"\n' "$vid" "$pid" "$alsa" >> "$RULE.tmp"
  # apply the id now (same sysfs attribute udev writes on the next plug); the card must be idle,
  # so MPD is paused around the write
  if [ "$id" != "$alsa" ]; then
    if systemctl is-active --quiet mpd; then systemctl stop mpd; RESTART_MPD=1; sleep 1; fi
    printf '%s' "$alsa" > "/sys/class/sound/card$idx/id" 2>/dev/null || warn "card$idx busy: name $alsa applies after re-plug/reboot"
  fi
  cat >> "$HIFI_DACS_CONF.tmp" <<EOC
[dac$n]
alsa_id=$alsa
name=$name
usb=$vid:$pid
rates=$rates
max_rate=$maxrate
max_bits=$bits
dsd=$dsd
mixer_control=$mixer
enabled=$([ $n -eq 1 ] && echo yes || echo no)
EOC
  log "DAC $n: $name ($vid:$pid) -> hw:CARD=$alsa | PCM to $maxrate Hz / $bits bit | DSD: $dsd | mixer: ${mixer:-none}"
done
mv "$RULE.tmp" "$RULE"; mv "$HIFI_DACS_CONF.tmp" "$HIFI_DACS_CONF"
udevadm control --reload
[ "${RESTART_MPD:-0}" = 1 ] && systemctl start mpd
log "wrote $RULE and $HIFI_DACS_CONF"
[ $SHOW -eq 1 ] && cat "$HIFI_DACS_CONF"
exit 0
